branch-defaults:
  javiers-branch:
    environment: mint-green
  main:
    environment: mint-green
    group_suffix: null
global:
  application_name: enhancemint
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
